"""initial schema

Revision ID: 8f6a19a46c61
Revises: 
Create Date: 2026-09-16 17:41:34.673842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6a19a46c61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # btree_gist adds GiST operator classes for scalar types (uuid, timestamptz,
    # ...), which the exclusion constraint on sla_pause_intervals needs to forbid
    # overlapping pause windows per SLA record - see DECISIONS.md D19.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sla_rules',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issue_priority'), nullable=False),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'priority', name='uq_sla_rules_category_priority')
    )
    op.create_table('sub_categories',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'id', name='uq_sub_categories_category_id_id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_sub_categories_category_name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_table('issues',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_USER', 'RESOLVED', 'CLOSED', name='issue_status'), nullable=False),
    sa.Column('ai_analysis_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_analysis_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issue_priority'), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('sub_category_id', sa.UUID(), nullable=True),
    sa.Column('current_team_id', sa.UUID(), nullable=True),
    sa.Column('current_resolver_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id', 'sub_category_id'], ['sub_categories.category_id', 'sub_categories.id'], name='fk_issues_category_sub_category'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_resolver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_ai_analysis_status'), 'issues', ['ai_analysis_status'], unique=False)
    op.create_index(op.f('ix_issues_current_resolver_id'), 'issues', ['current_resolver_id'], unique=False)
    op.create_index(op.f('ix_issues_current_team_id'), 'issues', ['current_team_id'], unique=False)
    op.create_index('ix_issues_current_team_status', 'issues', ['current_team_id', 'status'], unique=False)
    op.create_index(op.f('ix_issues_owner_id'), 'issues', ['owner_id'], unique=False)
    op.create_index(op.f('ix_issues_priority'), 'issues', ['priority'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('routing_rules',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('sub_category_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id', 'sub_category_id'], ['sub_categories.category_id', 'sub_categories.id'], name='fk_routing_rules_category_sub_category'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_routing_rules_category_only', 'routing_rules', ['category_id'], unique=True, postgresql_where='sub_category_id IS NULL')
    op.create_index('uq_routing_rules_category_sub_category', 'routing_rules', ['category_id', 'sub_category_id'], unique=True, postgresql_where='sub_category_id IS NOT NULL')
    op.create_table('issue_assignments',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('resolver_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_assignments_issue_id'), 'issue_assignments', ['issue_id'], unique=False)
    op.create_table('issue_comments',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    op.create_table('issue_status_history',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', sa.Enum('OPEN', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_USER', 'RESOLVED', 'CLOSED', name='issue_status'), nullable=True),
    sa.Column('new_status', sa.Enum('OPEN', 'TRIAGED', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_USER', 'RESOLVED', 'CLOSED', name='issue_status'), nullable=False),
    sa.Column('trigger', sa.Enum('SYSTEM_CREATE', 'MANUAL', 'AUTO_USER_REPLY', 'AI_ROUTING', 'ADMIN_OVERRIDE', name='status_change_trigger'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_status_history_issue_id'), 'issue_status_history', ['issue_id'], unique=False)
    op.create_table('sla_records',
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('sla_rule_id', sa.UUID(), nullable=False),
    sa.Column('sla_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_response_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_response_met_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_met_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accumulated_pause_seconds', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sla_rule_id'], ['sla_rules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_id')
    )
    op.create_table('sla_pause_intervals',
    sa.Column('sla_record_id', sa.UUID(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('sla_record_id'), '='), (sa.text("tstzrange(paused_at, COALESCE(resumed_at, 'infinity'), '[]')"), '&&'), using='gist', name='ex_sla_pause_intervals_no_overlap'),
    sa.CheckConstraint('resumed_at IS NULL OR resumed_at >= paused_at', name='ck_sla_pause_intervals_valid_range'),
    sa.ForeignKeyConstraint(['sla_record_id'], ['sla_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sla_pause_intervals_sla_record_id'), 'sla_pause_intervals', ['sla_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_pause_intervals_sla_record_id'), table_name='sla_pause_intervals')
    op.drop_table('sla_pause_intervals')
    op.drop_table('sla_records')
    op.drop_index(op.f('ix_issue_status_history_issue_id'), table_name='issue_status_history')
    op.drop_table('issue_status_history')
    op.drop_index(op.f('ix_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_table('issue_comments')
    op.drop_index(op.f('ix_issue_assignments_issue_id'), table_name='issue_assignments')
    op.drop_table('issue_assignments')
    op.drop_index('uq_routing_rules_category_sub_category', table_name='routing_rules', postgresql_where='sub_category_id IS NOT NULL')
    op.drop_index('uq_routing_rules_category_only', table_name='routing_rules', postgresql_where='sub_category_id IS NULL')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_priority'), table_name='issues')
    op.drop_index(op.f('ix_issues_owner_id'), table_name='issues')
    op.drop_index('ix_issues_current_team_status', table_name='issues')
    op.drop_index(op.f('ix_issues_current_team_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_current_resolver_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_ai_analysis_status'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sub_categories')
    op.drop_table('sla_rules')
    op.drop_table('teams')
    op.drop_table('roles')
    op.drop_table('categories')
    # ### end Alembic commands ###

    # Postgres ENUM types are standalone objects, not owned by any one table -
    # dropping the tables that used them does not drop the types themselves.
    # issue_priority and issue_status are each used by more than one table, so
    # they must only be dropped once, after every table using them is gone.
    for enum_name in ("issue_priority", "issue_status", "ai_analysis_status", "status_change_trigger"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
